-- MySQL Script generated by MySQL Workbench
-- 08/31/16 10:44:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pegpese
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pegpese
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pegpese` DEFAULT CHARACTER SET utf8 ;
USE `pegpese` ;

-- -----------------------------------------------------
-- Table `pegpese`.`atv_atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`atv_atividade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `data_atividade` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `TI` TINYINT(1) NULL DEFAULT NULL,
  `RH` TINYINT(1) NULL DEFAULT NULL,
  `finalizado` TINYINT(1) NULL DEFAULT '0',
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`atv_comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`atv_comentarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` LONGTEXT NULL DEFAULT NULL,
  `data_comentario` VARCHAR(20) NULL DEFAULT NULL,
  `id_atividade` INT(11) NOT NULL,
  `id_usuarios` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `id_usuarios`, `id_atividade`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_departamentos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `centro_custo` VARCHAR(45) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `cbo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_empresas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` LONGTEXT NULL DEFAULT NULL,
  `razao_social` LONGTEXT NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(45) NULL DEFAULT NULL,
  `Insc_Estadual` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_dados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_dados` (
  `codigo` INT(5) NOT NULL,
  `matricula` INT(5) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `data_admissao` VARCHAR(10) NULL DEFAULT NULL,
  `check` TINYINT(1) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `departamentos_codigo` INT(11) NOT NULL,
  `empresas_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `matricula`),
  INDEX `fk_dados_departamentos1_idx` (`departamentos_codigo` ASC),
  INDEX `fk_dados_empresas1_idx` (`empresas_codigo` ASC),
  CONSTRAINT `fk_dados_departamentos1`
    FOREIGN KEY (`departamentos_codigo`)
    REFERENCES `pegpese`.`rh_departamentos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dados_empresas1`
    FOREIGN KEY (`empresas_codigo`)
    REFERENCES `pegpese`.`rh_empresas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`emails` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `dados_codigo` INT(5) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_emails_dados_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_emails_dados`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gbo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gbo` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `dependencia` VARCHAR(45) NULL DEFAULT NULL,
  `n_boletim` VARCHAR(45) NULL DEFAULT NULL,
  `flagrante` TINYINT(1) NULL DEFAULT NULL,
  `iniciado_em` VARCHAR(10) NULL DEFAULT NULL,
  `vitima` LONGTEXT NULL DEFAULT NULL,
  `representante` LONGTEXT NULL DEFAULT NULL,
  `indiciado` LONGTEXT NULL DEFAULT NULL,
  `natureza` LONGTEXT NULL DEFAULT NULL,
  `local` LONGTEXT NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  `historico` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gsmartphone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gsmartphone` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `operadora` VARCHAR(45) NULL DEFAULT NULL,
  `imei` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `historico` LONGTEXT NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_cadastro` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `renavan` VARCHAR(45) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `chassi` VARCHAR(45) NULL DEFAULT NULL,
  `especie_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `cap_pot_cil` VARCHAR(45) NULL DEFAULT NULL,
  `categoria` VARCHAR(45) NULL DEFAULT NULL,
  `data_compra` VARCHAR(45) NULL DEFAULT NULL,
  `concessionaria` VARCHAR(45) NULL DEFAULT NULL,
  `ano_fabricacao` VARCHAR(45) NULL DEFAULT NULL,
  `ano_modelo` VARCHAR(45) NULL DEFAULT NULL,
  `km` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_dpvat_ipva_lic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_dpvat_ipva_lic` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `dpvat` TINYINT(1) NULL DEFAULT NULL,
  `ipva` TINYINT(1) NULL DEFAULT NULL,
  `licenciamento` TINYINT(1) NULL DEFAULT NULL,
  `exercicio` VARCHAR(45) NULL DEFAULT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  `data_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  `parcelas` VARCHAR(45) NULL DEFAULT NULL,
  `crlv` VARCHAR(45) NULL DEFAULT NULL,
  `data_emissao` VARCHAR(45) NULL DEFAULT NULL,
  `cadastro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `cadastro_codigo`),
  INDEX `testwe_idx` (`cadastro_codigo` ASC),
  CONSTRAINT `fk_gv_dpvat_ipva_lic_gv_cadastro`
    FOREIGN KEY (`cadastro_codigo`)
    REFERENCES `pegpese`.`gv_cadastro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_multa` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `condutor` VARCHAR(45) NULL DEFAULT NULL,
  `infracao` VARCHAR(45) NULL DEFAULT NULL,
  `local` VARCHAR(45) NULL DEFAULT NULL,
  `cod_loc_equip` VARCHAR(45) NULL DEFAULT NULL,
  `pontuacao` VARCHAR(45) NULL DEFAULT NULL,
  `vel_regular` VARCHAR(45) NULL DEFAULT NULL,
  `vel_media` VARCHAR(45) NULL DEFAULT NULL,
  `vel_considerada` VARCHAR(45) NULL DEFAULT NULL,
  `enquadramento` VARCHAR(45) NULL DEFAULT NULL,
  `hora` VARCHAR(45) NULL DEFAULT NULL,
  `just_legal` LONGTEXT NULL DEFAULT NULL,
  `data_infracao` VARCHAR(45) NULL DEFAULT NULL,
  `data_emissao` VARCHAR(45) NULL DEFAULT NULL,
  `artigo_ctb` VARCHAR(45) NULL DEFAULT NULL,
  `natureza` VARCHAR(45) NULL DEFAULT NULL,
  `n_ait` VARCHAR(45) NULL DEFAULT NULL,
  `data_defesa` VARCHAR(45) NULL DEFAULT NULL,
  `ident_equip` VARCHAR(45) NULL DEFAULT NULL,
  `afericao_certificado` VARCHAR(45) NULL DEFAULT NULL,
  `agente_transito` VARCHAR(45) NULL DEFAULT NULL,
  `cadastro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `cadastro_codigo`),
  INDEX `teste_idx` (`cadastro_codigo` ASC),
  CONSTRAINT `fk_gv_multa_gv_cadastro`
    FOREIGN KEY (`cadastro_codigo`)
    REFERENCES `pegpese`.`gv_cadastro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_preventiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_preventiva` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `km` INT(11) NULL DEFAULT NULL,
  `km_troca` INT(11) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `validade` TINYINT(1) NULL DEFAULT NULL,
  `data_troca` VARCHAR(10) NULL DEFAULT NULL,
  `data_validade` VARCHAR(10) NULL DEFAULT NULL,
  `troca` TINYINT(1) NULL DEFAULT '0',
  `cadastro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `cadastro_codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_seguro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_seguro` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `n_apolice` VARCHAR(45) NULL DEFAULT NULL,
  `n_proposta` VARCHAR(45) NULL DEFAULT NULL,
  `data_inicio` VARCHAR(45) NULL DEFAULT NULL,
  `data_termino` VARCHAR(45) NULL DEFAULT NULL,
  `cobertura_contrato` VARCHAR(45) NULL DEFAULT NULL,
  `obs_seguro` VARCHAR(45) NULL DEFAULT NULL,
  `valor_seguro` VARCHAR(45) NULL DEFAULT NULL,
  `valor_franquia` VARCHAR(45) NULL DEFAULT NULL,
  `form_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  `cadastro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `cadastro_codigo`),
  INDEX `fk_gv_seguro_gv_cadastro_idx` (`cadastro_codigo` ASC),
  CONSTRAINT `fk_gv_seguro_gv_cadastro`
    FOREIGN KEY (`cadastro_codigo`)
    REFERENCES `pegpese`.`gv_cadastro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`gv_sinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`gv_sinistro` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `culpado` VARCHAR(45) NULL DEFAULT NULL,
  `vitima` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `danos` VARCHAR(45) NULL DEFAULT NULL,
  `cadastro_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `cadastro_codigo`),
  INDEX `fk_gv_sinistro_gv_cadastro_idx` (`cadastro_codigo` ASC),
  CONSTRAINT `fk_gv_sinistro_gv_cadastro`
    FOREIGN KEY (`cadastro_codigo`)
    REFERENCES `pegpese`.`gv_cadastro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`ordem_servico` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `data_atendimento` VARCHAR(10) NULL DEFAULT NULL,
  `horarios` VARCHAR(10) NULL DEFAULT NULL,
  `atendimento` VARCHAR(45) NULL DEFAULT NULL,
  `solicitante` VARCHAR(45) NULL DEFAULT NULL,
  `aberto` VARCHAR(45) NULL DEFAULT NULL,
  `emitido` VARCHAR(45) NULL DEFAULT NULL,
  `fechado` VARCHAR(45) NULL DEFAULT NULL,
  `pendencias` TINYINT(1) NULL DEFAULT NULL,
  `previsto` LONGTEXT NULL DEFAULT NULL,
  `concluido` LONGTEXT NULL DEFAULT NULL,
  `setor` VARCHAR(45) NULL DEFAULT NULL,
  `rh_empresas_codigo` INT(11) NOT NULL,
  `rh_dados_codigo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`, `rh_empresas_codigo`),
  INDEX `fk_ordem_empresas_idx` (`rh_empresas_codigo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_adv_susp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_adv_susp` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data_adv_susp` VARCHAR(10) NULL DEFAULT NULL,
  `adv` TINYINT(1) NULL DEFAULT NULL,
  `susp` TINYINT(1) NULL DEFAULT NULL,
  `dias` VARCHAR(30) NULL DEFAULT NULL,
  `dias_ext` VARCHAR(45) NULL DEFAULT NULL,
  `retorno` VARCHAR(10) NULL DEFAULT NULL,
  `motivo` LONGTEXT NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 244
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_afastamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_afastamentos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  `data_inicial` VARCHAR(10) NULL DEFAULT NULL,
  `data_final` VARCHAR(10) NULL DEFAULT NULL,
  `data_retorno` VARCHAR(45) NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  `check` TINYINT(1) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_afastamentos_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_afastamentos_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_armarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_armarios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `obs` VARCHAR(45) NULL DEFAULT NULL,
  `n_armario` INT(11) NULL DEFAULT NULL,
  `ocupado` TINYINT(1) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_armarios_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_armarios_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 246
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_atestados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_atestados` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `dias` VARCHAR(45) NULL DEFAULT NULL,
  `horas` VARCHAR(45) NULL DEFAULT NULL,
  `injust` TINYINT(1) NULL DEFAULT NULL,
  `just` TINYINT(1) NULL DEFAULT NULL,
  `declaracao` TINYINT(1) NULL DEFAULT NULL,
  `atestado` TINYINT(1) NULL DEFAULT NULL,
  `sim` TINYINT(1) NULL DEFAULT NULL,
  `nao` TINYINT(1) NULL DEFAULT NULL,
  `motivo` LONGTEXT NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  `unidade` VARCHAR(45) NULL DEFAULT NULL,
  `int_sim` TINYINT(1) NULL DEFAULT NULL,
  `int_nao` TINYINT(1) NULL DEFAULT NULL,
  `hora_atendimento` VARCHAR(6) NULL DEFAULT NULL,
  `afast_sim` TINYINT(1) NULL DEFAULT NULL,
  `afast_nao` TINYINT(1) NULL DEFAULT NULL,
  `nat_lesao` VARCHAR(45) NULL DEFAULT NULL,
  `cid` VARCHAR(45) NULL DEFAULT NULL,
  `crm` VARCHAR(45) NULL DEFAULT NULL,
  `termino` VARCHAR(45) NULL DEFAULT NULL,
  `compareceu` TINYINT(1) NULL DEFAULT '0',
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_atestados_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_atestados_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1450
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_beneficios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `vale_transporte` TINYINT(1) NULL DEFAULT NULL,
  `bilhete1` VARCHAR(45) NULL DEFAULT NULL,
  `vt1` DOUBLE NULL DEFAULT NULL,
  `bilhete2` VARCHAR(45) NULL DEFAULT NULL,
  `vt2` DOUBLE NULL DEFAULT NULL,
  `bilhete3` VARCHAR(45) NULL DEFAULT NULL,
  `vt3` DOUBLE NULL DEFAULT NULL,
  `aux_combustivel` TINYINT(1) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `valor_vr` DOUBLE NULL DEFAULT NULL,
  `valor_va` DOUBLE NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_beneficios_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_beneficios_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 585
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_bilhetes_vt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_bilhetes_vt` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_cat` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `numCAT` VARCHAR(45) NULL DEFAULT NULL,
  `emitente` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_cat` VARCHAR(45) NULL DEFAULT NULL,
  `filiacao` VARCHAR(45) NULL DEFAULT NULL,
  `data_emissao` VARCHAR(10) NULL DEFAULT NULL,
  `comunicado_obito` VARCHAR(45) NULL DEFAULT NULL,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `hora_acidente` VARCHAR(6) NULL DEFAULT NULL,
  `hora_trabalho` VARCHAR(6) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `afastamento` VARCHAR(5) NULL DEFAULT NULL,
  `reg_policial` VARCHAR(5) NULL DEFAULT NULL,
  `local` VARCHAR(45) NULL DEFAULT NULL,
  `exp_local` VARCHAR(45) NULL DEFAULT NULL,
  `cgc` VARCHAR(45) NULL DEFAULT NULL,
  `uf_acidente` VARCHAR(2) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `ultimo_dia` VARCHAR(10) NULL DEFAULT NULL,
  `parte_corpo` VARCHAR(45) NULL DEFAULT NULL,
  `agente_causador` VARCHAR(45) NULL DEFAULT NULL,
  `sit_gerador` VARCHAR(45) NULL DEFAULT NULL,
  `morte` VARCHAR(3) NULL DEFAULT NULL,
  `data_obito` VARCHAR(10) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  `atestados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `atestados_codigo`, `dados_codigo`),
  INDEX `fk_cat_dados_idx` (`dados_codigo` ASC),
  INDEX `fk_cat_atestado_idx` (`atestados_codigo` ASC),
  CONSTRAINT `fk_cat_atestado`
    FOREIGN KEY (`atestados_codigo`)
    REFERENCES `pegpese`.`rh_atestados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cat_dados`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_contratos` (
  `codigo` INT(5) NOT NULL,
  `salario` DOUBLE NULL DEFAULT NULL,
  `dias_exp1` INT(11) NULL DEFAULT NULL,
  `exp1` VARCHAR(10) NULL DEFAULT NULL,
  `dias_exp2` INT(11) NULL DEFAULT NULL,
  `exp2` VARCHAR(10) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `demitido` VARCHAR(10) NULL DEFAULT NULL,
  `insalubridade` VARCHAR(10) NULL DEFAULT NULL,
  `horario_trabalho` LONGTEXT NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_contratos_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_contratos_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_contribuicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_contribuicoes` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `sindicato` VARCHAR(45) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_contribuicoes_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_contribuicoes_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_curriculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_curriculos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `data_nasc` VARCHAR(10) NULL DEFAULT NULL,
  `prov_nasc` TINYINT(1) NULL DEFAULT NULL,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `recebido` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(30) NULL DEFAULT NULL,
  `data_status` VARCHAR(10) NULL DEFAULT NULL,
  `feedback` LONGTEXT NULL DEFAULT NULL,
  `telefone` VARCHAR(14) NULL DEFAULT NULL,
  `empresas_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `empresas_codigo`),
  INDEX `fk_rh_empresas_idx` (`empresas_codigo` ASC),
  CONSTRAINT `fk_rh_empresas`
    FOREIGN KEY (`empresas_codigo`)
    REFERENCES `pegpese`.`rh_empresas` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1799
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_dependentes` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` LONGTEXT NULL DEFAULT NULL,
  `pensao_aliment` DOUBLE NULL DEFAULT NULL,
  `nascimento` VARCHAR(10) NULL DEFAULT NULL,
  `parentesco` VARCHAR(45) NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_dependentes_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_dependentes_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 400
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_documentos` (
  `codigo` INT(5) NOT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `data_emissao` VARCHAR(10) NULL DEFAULT NULL,
  `orgao_emissor` VARCHAR(45) NULL DEFAULT NULL,
  `pai` VARCHAR(45) NULL DEFAULT NULL,
  `mae` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `local_nascimento` VARCHAR(45) NULL DEFAULT NULL,
  `naturalidade` VARCHAR(45) NULL DEFAULT NULL,
  `cor_raca` VARCHAR(45) NULL DEFAULT NULL,
  `nacionalidade` VARCHAR(45) NULL DEFAULT NULL,
  `grau_instrucao` VARCHAR(45) NULL DEFAULT NULL,
  `data_nascimento` VARCHAR(10) NULL DEFAULT NULL,
  `estado_civil` VARCHAR(45) NULL DEFAULT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `cheg_brasil` VARCHAR(10) NULL DEFAULT NULL,
  `status_inst` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(45) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `fixo` VARCHAR(10) NULL DEFAULT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `celular` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `outros` VARCHAR(45) NULL DEFAULT NULL,
  `n_reservista` VARCHAR(45) NULL DEFAULT NULL,
  `ra_reservista` VARCHAR(45) NULL DEFAULT NULL,
  `serie_reservista` VARCHAR(45) NULL DEFAULT NULL,
  `dispensado` VARCHAR(10) NULL DEFAULT NULL,
  `ctps` VARCHAR(12) NULL DEFAULT NULL,
  `serie_carteira` VARCHAR(3) NULL DEFAULT NULL,
  `pis` VARCHAR(11) NULL DEFAULT NULL,
  `data_emissao_carteira` VARCHAR(10) NULL DEFAULT NULL,
  `uf_carteira` VARCHAR(2) NULL DEFAULT NULL,
  `insc_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `zona_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `secao_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `municipio_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `emissao_titulo` VARCHAR(10) NULL DEFAULT NULL,
  `banco` VARCHAR(45) NULL DEFAULT NULL,
  `agencia` VARCHAR(45) NULL DEFAULT NULL,
  `conta` VARCHAR(45) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_documentos_dados1_idx` (`dados_codigo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_epi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_epi` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `n_ca` VARCHAR(45) NULL DEFAULT NULL,
  `qtde` VARCHAR(45) NULL DEFAULT NULL,
  `entrega` VARCHAR(45) NULL DEFAULT NULL,
  `cod_fornec` VARCHAR(45) NULL DEFAULT NULL,
  `obs` VARCHAR(45) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_epi_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_epi_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 651
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_exames_e_outros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_exames_e_outros` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NULL DEFAULT NULL,
  `obs` VARCHAR(45) NULL DEFAULT NULL,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_exames_e_outros_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_exames_e_outros_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_faltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_faltas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `dias` INT(11) NULL DEFAULT NULL,
  `horas` VARCHAR(5) NULL DEFAULT NULL,
  `falta` TINYINT(1) NULL DEFAULT NULL,
  `atraso` TINYINT(1) NULL DEFAULT NULL,
  `motivo` LONGTEXT NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_faltas_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_faltas_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 161
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_ferias` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicial` VARCHAR(10) NULL DEFAULT NULL,
  `data_final` VARCHAR(10) NULL DEFAULT NULL,
  `check` TINYINT(1) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_ferias_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_ferias_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 745
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_folgas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_folgas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data_compra` VARCHAR(10) NULL DEFAULT NULL,
  `data_pagamento` VARCHAR(10) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `dados_codigo_pk_idx` (`dados_codigo` ASC),
  CONSTRAINT `dados_codigo_pk`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_habilitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_habilitacao` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `registro` VARCHAR(45) NULL DEFAULT NULL,
  `habilitacao1` VARCHAR(10) NULL DEFAULT NULL,
  `categoria` VARCHAR(4) NULL DEFAULT NULL,
  `validade` VARCHAR(10) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_habilitacao_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_habilitacao_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_historico_contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_historico_contratos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `empresa` VARCHAR(45) NULL DEFAULT NULL,
  `depart_carg` VARCHAR(45) NULL DEFAULT NULL,
  `base` DOUBLE NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_historico_dados_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_historico_dados`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_recibo_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_recibo_pagamentos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `descricao` LONGTEXT NULL DEFAULT NULL,
  `referencia` VARCHAR(45) NULL DEFAULT NULL,
  `provento` DOUBLE NULL DEFAULT '0',
  `desconto1` DOUBLE NULL DEFAULT '0',
  `descricao2` LONGTEXT NULL DEFAULT NULL,
  `referencia2` VARCHAR(45) NULL DEFAULT NULL,
  `provento2` DOUBLE NULL DEFAULT '0',
  `desconto2` DOUBLE NULL DEFAULT '0',
  `descricao3` LONGTEXT NULL DEFAULT NULL,
  `referencia3` VARCHAR(45) NULL DEFAULT NULL,
  `provento3` DOUBLE NULL DEFAULT '0',
  `desconto3` DOUBLE NULL DEFAULT '0',
  `descricao4` LONGTEXT NULL DEFAULT NULL,
  `referencia4` VARCHAR(45) NULL DEFAULT NULL,
  `provento4` DOUBLE NULL DEFAULT '0',
  `desconto4` DOUBLE NULL DEFAULT '0',
  `descricao5` LONGTEXT NULL DEFAULT NULL,
  `referencia5` VARCHAR(45) NULL DEFAULT NULL,
  `provento5` DOUBLE NULL DEFAULT '0',
  `desconto5` DOUBLE NULL DEFAULT '0',
  `descricao6` LONGTEXT NULL DEFAULT NULL,
  `referencia6` VARCHAR(45) NULL DEFAULT NULL,
  `provento6` DOUBLE NULL DEFAULT '0',
  `desconto6` DOUBLE NULL DEFAULT '0',
  `mensagens` LONGTEXT NULL DEFAULT NULL,
  `desconto` DOUBLE NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_recibo_pagamentos_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_recibo_pagamentos_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1861
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_td`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_td` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `treinamento` VARCHAR(45) NULL DEFAULT NULL,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `carg_horaria` VARCHAR(45) NULL DEFAULT NULL,
  `n_registro` VARCHAR(10) NULL DEFAULT NULL,
  `ministrado_por` VARCHAR(45) NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_td_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_td_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 405
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_uniformes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_uniformes` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_uniforme` VARCHAR(45) NULL DEFAULT NULL,
  `entrega` VARCHAR(10) NULL DEFAULT NULL,
  `qtde` INT(11) NULL DEFAULT NULL,
  `tm` VARCHAR(45) NULL DEFAULT NULL,
  `obs` LONGTEXT NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`),
  INDEX `fk_uniformes_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_uniformes_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2257
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`rh_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`rh_vagas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(11) NULL DEFAULT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `horario` VARCHAR(45) NULL DEFAULT NULL,
  `solicitado` VARCHAR(45) NULL DEFAULT NULL,
  `empresa` VARCHAR(45) NULL DEFAULT NULL,
  `data` VARCHAR(10) NULL DEFAULT NULL,
  `departamentos_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `departamentos_codigo`),
  INDEX `fk_departamentos_idx` (`departamentos_codigo` ASC),
  CONSTRAINT `fk_departamentos`
    FOREIGN KEY (`departamentos_codigo`)
    REFERENCES `pegpese`.`rh_departamentos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`storage` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nutricao` TINYINT(1) NULL DEFAULT NULL,
  `teste` TINYINT(1) NULL DEFAULT '0',
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`, `dados_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`system_checks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`system_checks` (
  `id` INT(11) NOT NULL,
  `system_version` VARCHAR(10) NULL DEFAULT NULL,
  `system_last_backup` VARCHAR(10) NULL DEFAULT NULL,
  `data_last_backup` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pegpese`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pegpese`.`usuarios` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT '0',
  `senha` VARCHAR(45) NULL DEFAULT '0',
  `funcionarios` TINYINT(1) NULL DEFAULT '0',
  `departamentos` TINYINT(1) NULL DEFAULT '0',
  `armarios` TINYINT(1) NULL DEFAULT '0',
  `administrador` TINYINT(1) NULL DEFAULT '0',
  `relatorios` TINYINT(1) NULL DEFAULT '0',
  `recibos` TINYINT(1) NULL DEFAULT '0',
  `empresas` TINYINT(1) NULL DEFAULT '0',
  `admin_rh` TINYINT(1) NULL DEFAULT '0',
  `alterar_rh` TINYINT(1) NULL DEFAULT '0',
  `veiculos` TINYINT(1) NULL DEFAULT '0',
  `emails` TINYINT(1) NULL DEFAULT '0',
  `ordem_servico` TINYINT(1) NULL DEFAULT '0',
  `bo` TINYINT(1) NULL DEFAULT '0',
  `smartphones` TINYINT(1) NULL DEFAULT '0',
  `dados_codigo` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_usuarios_dados1_idx` (`dados_codigo` ASC),
  CONSTRAINT `fk_usuarios_dados1`
    FOREIGN KEY (`dados_codigo`)
    REFERENCES `pegpese`.`rh_dados` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
